trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
          command: 'build'
          projects: '**/*.csproj'
          feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
          command: 'publish'
          publishWebProjects: true
    - task: Docker@2
      displayName: Build an Docker image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/RentMotorBike/Dockerfile'
        tags: |
          $(tag)
