services:
  postgres:
    image: postgres
    volumes:
      - ./01-CreateTables.sql:/docker-entrypoint-initdb.d/01-basegeografica.sql
    environment:
      POSTGRES_PASSWORD: "mypassword1234"
    ports:
      - "5432:5432"