version: '3.9'

services:
  rentmotorbike.api:
    image: ${DOCKER_REGISTRY-}rentmotorbikeapi
    build:
      context: .
      dockerfile: RentMotorBike.Api/Dockerfile
    ports:
    - "5000:5000"
    - "5001:5001"

  rentmotorbike.database:
    image: postgres:latest
    container_name: rentmotorbike.database
    environment:
       - POSTGRES_DB=base
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=mypassword1234
    volumes:
      - ./01-CreateTables.sql:/docker-entrypoint-initdb.d/01-CreateTables.sql
    ports:
      - "5432:5432"
    
