version: '3.9'

services:
  rentmotorbike.api:
    image: ${DOCKER_REGISTRY-}rentmotorbikeapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "5000:5000"
    - "5001:5001"

  rentmotorbike.database:
    image: postgres:latest
    container_name: rentmotorbike.database
    environment:
       - POSTGRES_DB=base
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=mypassword1234
    volumes:
      - ./01-CreateTables.sql:/docker-entrypoint-initdb.d/01-CreateTables.sql
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
    - 5672:5672
    - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
networks:
  rabbitmq_go_net:
    driver: bridge
    

    
